케라스; 마음대로 모델 짜기에는 불편함. 텐서플로우 편하게 만드는 거.

In [1]:
import torch

In [4]:
x = torch.randn(2,3)
x

tensor([[ 1.5759, -0.9716, -0.2952],
        [-0.9340,  0.0545, -0.3151]])

In [5]:
y = torch.zeros(2,3)
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

학습의 기준은 tensor라는 데이터타입. GPU에 사용하기 위해서임. gpu에 쓰면 학습속도가 빨라지기 때문.

In [10]:
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor)
# tensor의 최대값을 산출합니다.

x = torch.rand(2,3)
print(x)

# 최대값을 출력합니다.
print(torch.max(x))

# 해당 차원에서 최대값과 그 위치를 출력합니다.
print(torch.max(x,1))

# 위치를 출력합니다.
print(torch.max(x,1)[1])

tensor([[0.7374, 0.3207, 0.6260],
        [0.8130, 0.9279, 0.0432]])
tensor(0.9279)
(tensor([0.7374, 0.9279]), tensor([0, 1]))
tensor([0, 1])


In [11]:
# tensor.size()

x = torch.FloatTensor(10,12,3,3) #numpy의 shape와 비슷하다. 
# numpy 변수 넣어도 그대로 변환한다. 제로벡터 만들 때 쓰는 게 아니라, numpy 데이터 올리기 위해 쓴다.

print(x.size()[:])
print(x.size()[0])

torch.Size([10, 12, 3, 3])
10


numpy <-> tensor 변환이 자주 일어나기 때문에, numpy의 shape과 tensor의 size 유의.

In [ ]:
# batch matrix. batch size만큼 학습하고 backpropagation을 진행하는데, 
# 3*4 데이터 10개, 4 *5 데이터 10개. => batch끼리 행렬곱 연산을 진행할 때 -> 이 경우 3*5 matrix가 나온다.
x1 = torch.rand(10,3,4)
# batch size가 10이라는 뜻.

x2 = torch.rand(10,4,5)

torch.bmm(x1,x2).size()

In [12]:
# view = 1 col vector로 바꿔주는 연산.
# view()

x = torch.randn(4,4)
y = x.view(-1)
z = x.view(-1,8) # -1의 경우 다른 차원들로 유추합니다. 이 경우에는 2로 유추합니다.
print(x.size())
print(y.size(),y)
print(z.size(),z)

torch.Size([4, 4])
torch.Size([16]) tensor([ 0.4028,  0.6694, -1.3955, -0.8514,  0.6363, -0.2164,  0.0162,  1.2773,
        -1.9124,  0.0408, -0.2800,  0.4008,  0.2107,  0.2624,  0.6135, -0.1653])
torch.Size([2, 8]) tensor([[ 0.4028,  0.6694, -1.3955, -0.8514,  0.6363, -0.2164,  0.0162,  1.2773],
        [-1.9124,  0.0408, -0.2800,  0.4008,  0.2107,  0.2624,  0.6135, -0.1653]])


In [13]:
torch.cuda.is_available()

False

In [14]:
# squeeze = dimension에서 1인 것만 지워내는 역할.

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim

from torch.autograd import Variable
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision import datasets

In [16]:
batch_size = 32
learning_rate = 0.01
num_epochs = 5

In [17]:
train_dataset = datasets.MNIST(root='./data',train=True, transform=transforms.ToTensor(),download=True)

Processing...
Done!


In [20]:
test_dataset = datasets.MNIST(root='./data',train=False, transform=transforms.ToTensor())

In [21]:
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle = True)

In [22]:
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)

In [35]:
class Neuralnetwork(nn.Module):
    def __init__(self, num_classes=10):
        super(Neuralnetwork,self).__init__()
        self.layer1 = nn.Linear(28*28, 100)
        self.layer2 = nn.Linear(100,200)
        self.layer3 = nn.Linear(200, num_classes)
    def forward(self,x):
        out = x.view(x.size(0),-1) # Fully connected를 쓰기 위해 view를 사용
        out = self.layer1(out)
        out = self.layer2(out)
        out = self.layer3(out)
        return out

In [36]:
model = Neuralnetwork()

In [37]:
criterion = nn.CrossEntropyLoss()

In [38]:
optimizer = optim.SGD(model.parameters(), lr = learning_rate)

In [ ]:
for epoch in range(num_epochs):
    for i, (img,label) in enumerate(train_loader, 1):
        img, label = Variable(img), Variable(label)
        out = model(img)
        loss = criterion(out, label)
        
        #학습하는 3개의 함수. 외운다
        optimizer.zero_grad() # 이전까지 했던 grad 초기화
        loss.backward() # backprop
        optimizer.step()
        
        if (i+1) % 100 ==0:
            
        